CREATE SCHEMA IF NOT EXISTS tri;

DROP TABLE IF EXISTS tri.type_5;

CREATE TABLE tri.type_5 (
       "trifid" varchar, 
       "document_control_number" bigint, 
       "cas_number" varchar, 
       "chemical_name" varchar, 
       "classification" varchar, 
       "reporting_year" integer, 
       "facility_name" varchar, 
       "facility_street" varchar, 
       "facility_city" varchar, 
       "facility_county" varchar, 
       "facility_state" varchar, 
       "facility_zip_code" varchar, 
       "facility_bia_code" integer, 
       "facility_bia_name" varchar, 
       "entire_facility_ind" boolean, 
       "partial_facility_ind" boolean, 
       "federal_facility_ind" boolean, 
       "goco_facility_ind" boolean, 
       "primary_sic_code" varchar, 
       "sic_code_2" varchar, 
       "sic_code_3" integer, 
       "sic_code_4" integer, 
       "sic_code_5" integer, 
       "sic_code_6" varchar, 
       "naics_origin" varchar, 
       "primary_naics_code" varchar, 
       "naics_code_2" integer, 
       "naics_code_3" integer, 
       "naics_code_4" integer, 
       "naics_code_5" integer, 
       "naics_code_6" integer, 
       "latitude" float, 
       "longitude" float, 
       "db_nr_a" varchar, 
       "db_nr_b" varchar, 
       "rcra_nr_a" varchar, 
       "rcra_nr_b" varchar, 
       "npdes_nr_a" varchar, 
       "npdes_nr_b" varchar, 
       "uic_nr_a" varchar, 
       "uic_nr_b" varchar, 
       "parent_company_name" varchar, 
       "parent_company_db_nr" varchar, 
       "section_8.11_disposal_or_other_releases,_source_reduction,_and_recycling_activities" varchar, 
       "assigned_fed._facility_flag" boolean, 
       "public_contact_email" varchar, 
       "revision_code_1" varchar, 
       "revision_code_2" varchar, 
       "metal_indicator" boolean
  
);
