CREATE SCHEMA IF NOT EXISTS manifest;

DROP TABLE IF EXISTS manifest.new_york;
CREATE TABLE manifest.new_york(
	"manifest_tracking_num" varchar(12),
	"page_num" float,
	"line_item_num" float,
	"gen_rcra_id" varchar(12),
	"gen_sign_date" date,
	"tsdf_rcra_id" varchar(12),
	"tsdf_sign_date" date,
	"transporter_1_rcra_id" varchar(12),
	"transporter_1_sign_date" date,
	"transporter_2_rcra_id" varchar(12), 
	"transporter_2_sign_date" date, 
	"import_ind" boolean, 
	"export_ind" boolean,
	"discr_quantity_ind" boolean,
	"discr_type_ind" boolean,
	"discr_residue_ind" boolean,
	"discr_partial_reject_ind" boolean,
	"discr_full_reject_ind" boolean,
	"manifest_ref_num" varchar(12), 
	"alt_facility_rcra_id" varchar(32), 
	"alt_facility_sign_date" varchar(32), 
	"num_of_containers" float,
	"container_type_code" varchar(2),
	"waste_qty" float,
	"unit_of_measure" varchar(1),
	"specific_gravity" float,
	"handling_type_code" varchar(1),
	"mgmt_method_type_code" varchar(4),
	"waste_code_1" varchar(4), 
	"waste_code_2" varchar(4), 
	"waste_code_3" varchar(4), 
	"waste_code_4" varchar(4), 
	"waste_code_5" varchar(4), 
	"waste_code_6" varchar(4)
);
